export type Difficulty = "easy" | "medium" | "hard" | "impossible" | "pokemonGen1" | "slayTheSpire1" | "smash" | "disney" | "myth"
| "borrowed" | "food" | "household";

export const WORD_LISTS: Record<Difficulty, string[]> = {
  easy: [
    "airport", "apple", 
    "backpack", "backyard", "ball", "banana", "bank", "basement", 
    "bathroom", "beach", "bed", "bedroom", "blanket", "boat", "book", "bottle", "broom", "bucket", "burger", 
    "cake", "candle", "candy", "car", "card", "chair", "classroom", "cat", "chocolate",
    "clock", "cloud", "comb", "cookie", "crayon", "cup", "cherry",
    "dog", "door", "drum", 
    "egg", 
    "farm", "fence", "fire", "flower", "fork", "forest", 
    "garage", "garden", "glue", "grass", 
    "hammer", "hat", "heart", "hospital", "hotel", "house", 
    "ice cream", "island", 
    "juice", "jacket",
    "key", "kitchen", "kite", "knife", 
    "ladder", "lake", "lamp", "library", "living room", 
    "mall", "marker", "milk", "mirror", "moon", "mountain", 
    "movie theater", "museum", 
    "notebook", 
    "ocean",  
    "pancake", "paper", "park", "pencil", "penny", "phone", "piano", 
    "pillow", "pizza", "plant", "plate", "playground", "pool", "pen",
    "restaurant", 
    "sandwich", "school", "scissors", "shoe", "soap", 
    "socks", "spoon", "stove", "sun", 
    "table", "toothbrush", "toothpaste", "toy", "train", "tree", "truck", "towel", 
    "wallet", "water", 
  ],
  medium: [
    "accordion", "airplane", "alligator", "almond", "Amazon", "anchor", "Albert Einstein", "apron", "aquarium", "arrow", "Avengers", "avocado", 
    "badge", "bakery", "balloon", "barbecue", "barn", "baseball", "basket", "Batman", "beaver", "beehive", "bench", "Barbie",
    "binoculars", "blender", "blueberry", "boathouse", "bookstore", "bowling alley", "bracelet", "bridge", "broccoli", "bubblegum", 
    "cabin", "cactus", "calendar", "camera", "canoe", "caramel", "carrot", "cartoon", "castle",
    "catfish", "ceiling fan", "chimney", "cinnamon", "circus", "cliff", "Coca-Cola", "compass",
    "cookie dough", "coral reef", "cottage", "crayon box", "crow", "cupcake", 
    "daffodil", "dandelion", "dartboard", "desert", "diner", "dolphin", "dragonfly", "drumstick", "Disneyland",
    "eagle", "earmuffs", "eggplant", "escalator", "Eiffel Tower",
    "Facebook", "ferry", "fireplace", "fishing pier", "flamingo", "floodlight", "flower shop", "fountain", "fox", 
    "globe", "goose", "grapefruit", "greenhouse", "guitar", "Grand Canyon", "Great Wall of China", "George Washington", "Google",
    "hamster", "hedgehog", "helmet", "honeycomb", "hot air balloon", "Hulk", "Hollywood",
    "ice rink", "igloo", "Instagram", 
    "jellybean", "jungle", 
    "kayak", "kettle", "kiwi", 
    "ladder", "lake", "lantern", "laundromat", "lemonade", "library", "Lego", "lighthouse", "lobster", 
    "magnet", "Mario", "meadow", "mermaid", "milkshake", "minivan", "monkey", "museum", "Mona Lisa", "Mount Everest", "Microsoft", "Mickey Mouse", 
    "nachos", "Netflix", "New York City", "noodle bowl", 
    "observatory", "octopus", "orchard", "otter", 
    "pancake", "parrot", "peacock", "peppermint", "pier", "pineapple", "plaza", "popcorn", "pretzel", "Pacific Ocean", "Pablo Picasso",
    "quilt", 
    "rainforest", "recycling bin", "resort", "robot", "roller coaster", 
    "sailboat", "sandcastle", "scarecrow", "school bus", "seashell", "Sesame Street", "shampoo",
    "skate park", "Snoopy", "snowman", "soccer field", "sparrow", "spatula", "Spider-Man", "squirrel", "stadium", "Statue of Liberty",
    "Starbucks", "subway", "sunflower", "surfboard", "sushi", "swamp", 
    "telescope", "tent", "tiger", "tornado", "tower", "tractor", "train station", "trombone", "tunnel", "turtle", 
    "Taylor Swift", "Times Square",
    "unicorn", 
    "valley", "volcano",
    "waffle", "waterfall", "whale", "Walmart", "windmill", "Winnie the Pooh", "woodpecker", "William Shakespeare", 
    "yogurt", "YouTube",
    "zebra", "zipper"
  ],
  hard: [
    "abyss", "Achilles", "Aesop", "Aphrodite", "alchemy", "allegiance", "Alcatraz", "amphibian", "amphitheater",
    "anatomy", "anomaly", "archipelago", "artichoke", "artifact", "astronaut", "astronomy", "avalanche",
    "bagpipes", "baguette", "barricade", "basilisk", "battalion", "beacon", "Beethoven", "bestiary", "blizzard",
    "boomerang", "brimstone", "burrow", 
    "cadence", "calamity", "carnivore", "catacomb", "chandelier", "chasm", "chisel", "chronicle", "cipher", "citadel", 
    "Cleopatra", "Colosseum", "conundrum", "corkscrew", "cosmos", "crescendo", "crimson", "crypt", "cyclone", 
    "Da Vinci", "decibel", "Dead Sea", "doppelganger", "dormant", "Dumbledore", "Darth Vader", "Dracula", 
    "eclipse",  "element", "emblem", "enigma", "epiphany", "epoch", "equator", "erosion", "escalator",  "espresso", "ethereal", 
    "faction", "fissure", "fondue", "fortitude", "Frida Kahlo", "frenzy", "frostbite", "fugitive", "furnace", 
    "Galileo", "garrison", "gauntlet", "gazebo", "Genghis Khan", "glacier", "gluttony", "golem", "gondola", "gravity", "Grand Canyon", 
    "harbinger", "havoc", "helix", "Hercules", "Houdini", "hurricane", 
    "illusion", "immortal", "impulse", "inertia", "infinity", "insignia", "instinct", "intrigue", "ironclad", 
    "javelin", 
    "kayak", "keystone", "kimono", "kombucha", 
    "labyrinth", "leviathan", "lore", 
    "macaron", "maelstrom", "Machu Picchu", "mandolin", "manifesto", "maracas", "Marie Curie", "mariner", "metamorphosis", 
    "metronome", "Machu Picchu", "mirage", "monolith", "Mount Rushmore",
    "nebula", "nemesis", "Nikola Tesla", "nocturnal", "nomad", 
    "obsidian", "octopus", "Odysseus", "omen", "oracle", "origami", "outpost", 
    "Panama Canal", "Pandora", "paradox", "paragon", "Parthenon", "pendulum", "Perseus", "phantom", "pilgrimage", 
    "pistachio", "plague", "pomegranate", "precipice", "prophecy",
    "quarry", "quiver", 
    "radiance", "rampart", "raptor", "relic", "reverie", "rift", "ritual", "Robin Hood", "runestone", 
    "saga", "sanctum", "sauerkraut", "sentinel", "serpent", "shard", "siege", "silhouette", "solstice", "souvenir", "sovereign", 
    "spatula", "specter", "sphinx", "spire", "stethoscope", "Stonehenge", "stratosphere", "summit", "sundial", "syndrome", 
    "tambourine", "telescope", "tempest", "terrarium", "tetanus", "tether", "threshold", "tiger shark", "tiramisu", "titan", 
    "torment", "traverse", "treadmill", "tundra", "tyrant", 
    "umbra", "undertow", "vanguard", "Vatican City", "venom", "verdict", "Voldemort", "vortex", 
    "warlord", "wasteland", "whirlpool", "Willy Wonka", "wraith", 
    "zephyr", "zenith", "zinc", "zircon", "zucchini", "Zorro"
  ],
  impossible: [
    "abacus", "abstraction", "access", "adaptation", "adjacency", "aftereffect", "algorithm",
    "ambiguity", "analysis", "anecdote", "anomaly", "anthology", "apathy",
    "apex", "archetype", "Area 51", "artifact", "ascension", "ash", "aspect", "atmosphere", "Atlantis", "aura",
    "Ada Lovelace", "Alan Turing", "Amelia Earhart", "atmosphere",
    "balance", "belief", "Bermuda Triangle", "bias", "Blackbeard", "boundary", "budget", "bureaucracy", 
    "cadence", "cause", "center", "charisma", "charge", "choice", "chronology", "cipher", "climate", "community", "complexity", 
    "concept", "conscience", "consensus", "context", "contrast", "control", "culture", "cycle", 
    "dark horse", "data", "decay", "definition", "demand", "desire", "destiny", "detail", "determinism", "dimension", "discourse", 
    "disparity", "distance", "draft", "drift", "dust", 
    "echo", "effect", "emotion", "empathy", "entropy", "equilibrium", "essence", "ethics", "evidence", 
    "evolution", "exception", "experience", "factor", "fear", "feedback", "field", "fine print", "Fibonacci", "flame", "focus", 
    "foam", "force", "form", "frame", "frequency", "function", 
    "galaxy", "gateway", "genre", "government", "grain", "growth", 
    "habit", "Harriet Tubman", "harmony", "heuristic", "history", "horizon", "hypothesis", 
    "idea", "identity", "impact", "impulse", "incentive", "inference", "infinity", "inkwell", "instinct",
    "intention", "interaction", "interpretation", "irony", 
    "Jane Austen", 
    "karma", "knowledge", "Kyoto", "layer",
    "limit", "limbo", "loophole", "Luxembourg", 
    "market", "Mary Shelley", "matter", "meaning", "mechanism", "memory", "metaphor", "method", "Mongolia", 
    "momentum", "Monet", "moss", "motion", "Murphy's law", "mystique",
    "nature", "necessity", "nostalgia", "notion", 
    "observation", "Occam's razor", "ocean", "offset", "origin", "Ssaka", "Oscar Wilde", "outcome", 
    "parallel", "pattern", "perception", "perspective", "phenomenon", "philosophy", "plot twist", "Pythagoras", 
    "quality", "Quebec", "quill", "range", "Rasputin", "reaction", "reason", "red herring", "reflection", "reputation", "resolution", 
    "resource", "risk", "Rosetta Stone", "root", 
    "Sahara Desert", "Scherodinger's cat", "season", "Sicily", "Signal", "Sisyphus", "society", "space", "stereoscope", "steam", 
    "structure", "substance", "supply", "surface", "symbol", "system", 
    "tension", "technology", "tendency", "theory", "thread", "thought", "trade", "tradition", "Trojan Horse", "truth", "turbulence", 
    "union", "Uluru", 
    "value", "Vancouver", "variable", "version", "vibration", "volume", 
    "wave", "wealth", "weather", "will", "wisdom", "wonder", "world", 
    "z-axis", "zen", "zero", "zone",
  ],
  pokemonGen1: [
    "Abra", "Aerodactyl", "Alakazam", "Arbok", "Arcanine",
    "Articuno", "Beedrill", "Bellsprout", "Blastoise", "Bulbasaur",
    "Butterfree", "Caterpie", "Chansey", "Charizard", "Charmander",
    "Charmeleon", "Clefable", "Clefairy", "Cloyster", "Cubone",
    "Dewgong", "Diglett", "Ditto", "Dodrio", "Doduo",
    "Dragonair", "Dragonite", "Dratini", "Drowzee", "Dugtrio",
    "Eevee", "Ekans", "Electabuzz", "Electrode", "Exeggcute",
    "Exeggutor", "Farfetch’d", "Fearow", "Flareon", "Gastly",
    "Gengar", "Geodude", "Gloom", "Golbat", "Goldeen",
    "Golduck", "Golem", "Graveler", "Grimer", "Growlithe",
    "Gyarados", "Haunter", "Hitmonchan", "Hitmonlee", "Horsea",
    "Hypno", "Ivysaur", "Jigglypuff", "Jolteon", "Jynx",
    "Kabuto", "Kabutops", "Kadabra", "Kakuna", "Kangaskhan",
    "Kingler", "Koffing", "Krabby", "Lapras", "Lickitung",
    "Machamp", "Machoke", "Machop", "Magikarp", "Magmar",
    "Magnemite", "Magneton", "Mankey", "Marowak", "Meowth",
    "Metapod", "Mew", "Mewtwo", "Moltres", "Mr. Mime",
    "Muk", "Nidoking", "Nidoqueen", "Nidoran♀", "Nidoran♂",
    "Nidorina", "Nidorino", "Ninetales", "Oddish", "Omanyte",
    "Omastar", "Onix", "Paras", "Parasect", "Persian",
    "Pidgeot", "Pidgeotto", "Pidgey", "Pikachu", "Pinsir",
    "Poliwag", "Poliwhirl", "Poliwrath", "Ponyta", "Porygon",
    "Primeape", "Psyduck", "Raichu", "Rapidash", "Raticate",
    "Rattata", "Rhydon", "Rhyhorn", "Sandshrew", "Sandslash",
    "Scyther", "Seadra", "Seaking", "Seel", "Shellder",
    "Slowbro", "Slowpoke", "Snorlax", "Spearow", "Squirtle",
    "Starmie", "Staryu", "Tangela", "Tauros", "Tentacool",
    "Tentacruel", "Vaporeon", "Venomoth", "Venonat", "Venusaur",
    "Victreebel", "Vileplume", "Voltorb", "Vulpix", "Wartortle",
    "Weedle", "Weepinbell", "Weezing", "Wigglytuff", "Zapdos",
    "Zubat"
  ],
  slayTheSpire1: [
    "Accuracy", "Acrobatics", "Adrenaline", "After Image", "Aggregate", "All For One", "All Out Attack", "Alpha", "Amplify", "Anger",
    "Apotheosis", "Armaments", "Auto Shields", "Backflip", "Backstab", "Ball Lightning", "Bandage Up", "Bane",
    "Barrage", "Barricade", "Bash", "Battle Hymn", "Battle Trance", "Beam Cell", "Become Almighty", "Berserk", "Biased Cognition", "Bite",
    "Blade Dance", "Blasphemy", "Blizzard", "Blood for Blood", "Bloodletting", "Bloodshot", "Bludgeon", "Blur", "Body Slam", "Bolt from the Blue",
    "Boot Sequence", "Bouncing Flask", "Brilliance", "Brutality", "Buffer", "Bullet Time", "Burn", "Burning Pact", "Burst", "Calculated Gamble",
    "Calm", "Capacitor", "Carnage", "Carve Reality", "Catalyst", "Chill", "Choke", "Clash", "Cleave", "Clothesline",
    "Cold Snap", "Collect", "Combust", "Concentrate", "Conclude", "Conjure Blade", "Conserve Battery", "Consecrate", "Consume",
    "Contact", "Coolheaded", "Core Surge", "Corpse Explosion", "Creative AI", "Crescendo", "Crippling Cloud", "Crush Joints",
    "Cut Through Fate", "Dagger Spray", "Dagger Throw", "Dark Embrace", "Dark Shackles", "Darkness", "Dash", "Deadly Poison",
    "Deceive Reality", "Defend", "Deflect", "Defragment", "Demon Form", "Deus Ex Machina", "Devotion", "Die Die Die", "Disarm", "Discovery", "Distraction",
    "Divide", "Dodge and Roll", "Doom and Gloom", "Doppelganger", "Double Energy", "Double Tap", "Dramatic Entrance", "Dropkick", "Dual Cast",
    "Dual Wield", "Duct Tape", "Echo Form", "Electrodynamics", "Empty Body", "Empty Fist", "Empty Mind", "Enlightenment", "Envenom", "Eruption",
    "Escape Plan", "Establishment", "Evaluate", "Eviscerate", "Evolve", "Exhume", "Expertise", "Fame and Fortune", "Fasting", "Fear No Evil",
    "Feed", "Feel No Pain", "Finesse", "Finisher", "Fire Breathing", "Flame Barrier", "Flash of Steel", "Flechettes", "Flex", "Flurry of Blows",
    "Flying Knee", "Flying Sleeves", "Footwork", "Force Field", "Foresight", "Forethought", "Fission", "Fist of Iron", "Flurry",
    "Fusion", "Gash", "Genetic Algorithm", "Ghostly Armor", "Glacier", "Glass Knife", "Go for the Eyes", "Good Instincts", "Grand Finale", "Halt",
    "Hand of Greed", "Havoc", "Headbutt", "Heel Hook", "Hello World", "Hemokinesis", "Hologram", "Hope", "Hyperbeam", "Immolate",
    "Impatience", "Impervious", "Indignation", "Infernal Blade", "Inflame", "Infinite Blades", "Inner Peace", "Insight", "Intimidate", "Iron Wave",
    "Jack of All Trades", "Judgment", "Just Lucky", "Leap", "Leg Sweep", "Like Water", "Limit Break", "Lock-On", "Loop", 
    "Madness", "Magnetism", "Malaise", "Master of Strategy", "Master Reality", "Mayhem", "Meditate", "Melter",
    "Metallicize", "Metamorphosis", "Mind Blast", "Mind Blast+", "Mind Blast++", "Miracle", "Multi-Cast", "Neutralize", "Nightmare", "Nirvana",
    "Nocturnal", "Offering", "Omniscience", "Outmaneuver", "Overclock", "Panacea", "Panache", "Pandemonium", 
    "Perfected Strike", "Perseverance", "Phantasmal Killer", "Piercing Wail", "Poisoned Stab", "Pommel Strike", "Power Through",
    "Predator", "Prepared", "Pressure Points", "Pride", "Prostrate", "Protect", "Pummel", "Purge", "Purity", "Quick Slash",
    "Ragnarok", "Rampage", "Reach Heaven", "Reaper", "Rebound", "Reboot", "Rebound", "Recursion", "Recycle", "Redo",
    "Reflex", "Reinforced Body", "Reprogram", "Riddle With Holes", "Rip and Tear", "Ritual Dagger", "Rupture", "Rushdown", "Sadistic Nature",
    "Sanctity", "Sands of Time", "Sash Whip", "Scrawl", "Scrape", "Searing Blow", "Second Wind", "Secret Technique", "Secret Weapon", "Seeing Red",
    "Searing Blow", "Self Repair", "Sentinel", "Setup", "Sever Soul", "Shiv", "Shockwave", "Shrug It Off", 
    "Silent", "Simmering Fury", "Skewer", "Skim", "Slice", "Smite", "Sneaky Strike", "Spire Growth",
    "Spirit Shield", "Spot Weakness", "Stack", "Static Discharge", "Steam", "Steam Barrier", "Storm", "Strike", "Study", "Sunder",
    "Survivor", "Sweeping Beam", "Swivel", "Sword Boomerang", "Tactician", "Tantrum", "Tempest", "Terror", "The Bomb", "Third Eye",
    "Thorns", "Thunderclap", "Thunder Strike", "Tidal Wave", "Tools of the Trade", "Torment", "Transmutation", "Trip", "True Grit", "Turbo",
    "Twin Strike", "Uppercut", "Vault", "Venomology", "Vigilance", "Violence", "Void", "Wallop", "Warcry", "Wave of the Hand", "Weave",
    "Well-Laid Plans", "Wheel Kick", "Whirlwind", "White Noise", "Wild Strike", "Wish", "Worship", "Wraith Form", "Writhe",
    "Zap",
  ],
  smash: [
    "Banjo & Kazooie", "Bayonetta", "Bowser", "Bowser Jr.", "Byleth",
    "Captain Falcon", "Chrom", "Cloud", "Corrin",
    "Daisy", "Dark Pit", "Dark Samus", "Diddy Kong", "Donkey Kong", "Dr. Mario", "Duck Hunt",
    "Falco", "Fox",
    "Ganondorf", "Greninja",
    "Hero",
    "Ice Climbers", "Ike", "Incineroar", "Inkling", "Isabelle",
    "Jigglypuff", "Joker",
    "Kazuya", "Ken", "King Dedede", "King K. Rool", "Kirby",
    "Link", "Little Mac", "Lucario", "Lucas", "Lucina", "Luigi",
    "Mario", "Marth", "Mega Man", "Meta Knight", "Mewtwo", "Mii Brawler", "Mii Gunner", "Mii Swordfighter", "Mr. Game & Watch",
    "Ness",
    "Olimar",
    "Pac‑Man", "Palutena", "Peach", "Pichu", "Pikachu", "Piranha Plant", "Pit", "Pokémon Trainer",
    "Richter", "Ridley", "R.O.B.", "Robin", "Rosalina & Luma", "Roy", "Ryu",
    "Samus", "Sephiroth", "Sheik", "Shulk", "Simon", "Snake", "Sonic", "Sora",
    "Steve",
    "Terry", "Toon Link",
    "Villager",
    "Wario", "Wii Fit Trainer", "Wolf",
    "Yoshi",
    "Young Link",
    "Zelda", "Zero Suit Samus" 
  ],
  disney: [
    "Abby Mallard", "Abu", "Adella", "Aladdin", "Alameda Slim", "Alice", "Amelia (Treasure Planet)", "Amos Slade", "Andy", 
    "Anger", "Anna", "Anton Ego", "Aphrodite (Hercules)", "Ariel", "Arlo",
    "Bagheera", "Bailey (Finding Dory)", "Baloo", "Bambi", "Bashful", "Baymax", "Beast", "Becky (Finding Dory)", "Belle", 
    "Berlioz", "Bernard", "Bianca", "Bing Bong", "Bloat", "Bo Peep", "Bolt", "Boo", "Bruce", "Bruno Madrigal", "Bubbles", 
    "Bucky (Zootopia)", "Buzz Lightyear",
    "Cad Spinner", "Cale (Treasure Planet)", "Callaghan", "Camilo Madrigal", "Carl Fredricksen", "Celia Mae", "Cinderella", 
    "Clawhauser", "Cleo", "Cobra Bubbles", "Cogsworth", "Colette", "Copper", "Cruella de Vil",
    "Dash Parr", "Davy Jones", "Dewey", "Digger (Cars)", "Django", "Doc (Snow White)", "Doc Hudson", "Donald Duck", "Dopey", 
    "Dory", "Duchess", "Dug", "Dumbo",
    "Earl Devereaux", "Eeyore", "Elastigirl", "Ellie Fredricksen", "Elsa", "Emperor Kuzco", "Emile", "Esmeralda", "EVE",
    "Fairy Godmother", "Faline", "Fawn", "Fear", "Felix (Wreck‑It Ralph)", "Figaro", "Fillmore", "Finnick", "Flik", "Flora", 
    "Flounder", "Flynn Rider", "Frozone",
    "Gabby Gabby", "Gaston", "Genie", "Geppetto", "Gideon Grey", "Gil (Finding Nemo)", "Go Go Tomago", "Goofy", "Gramma Tala", "Gus Gus",
    "Hades", "Hamm", "Hans", "Hank (Finding Dory)", "Hector (Coco)", "Hercules", "Hiro Hamada", "Honeymaren", "Hopper",
    "Ichabod Crane",
    "Jack Jack", "Jack Skellington", "Jackson Storm", "Jafar", "Jane Porter", "Jasmine", "Jessie", "Jim Hawkins", "Jiminy Cricket", 
    "Joe Gardner", "John Silver", "Joy", "Judy Hopps",
    "Kala", "Kanga", "Karamel (Ralph Breaks the Internet)", "Katrina Van Tassel", "Kermit", "Kida", "King Candy", "King Fergus", 
    "King Louie", "King Triton", "Kristoff",
    "Lady", "Lafayette", "Lance Strongbow", "Lenny (Toy Story)", "Lewis (Meet the Robinsons)", "Lilo", "Lightning McQueen", 
    "Li Shang", "Ling", "Louie", "Lucifer (Cinderella)", "Lumière", "Luisa Madrigal",
    "Mad Hatter", "Maestro Forte", "Maleficent", "Mama Odie", "Marlin", "Mary Poppins", "Mater", "Maurice", "Maximus", 
    "Meeko", "Megara", "Melody", "Merida", "Merryweather", "Mickey Mouse", "Miguel Rivera", "Mike Wazowski", "Milo Thatch", 
    "Minnie Mouse", "Mittens", "Moana", "Mowgli", "Mulan", "Mushu",
    "Nala", "Nana", "Nemo", "Nick Wilde", "Nigel (Finding Nemo)", "Nita (Brother Bear 2)",
    "Olaf", "Oliver", "Oogie Boogie", "Orville",
    "Pain", "Panchito", "Pascal", "Pegasus", "Penny (Bolt)", "Penny (Rescuers)", "Perdita", "Peter Pan", "Phil", "Philippe", 
    "Philoctetes", "Pinocchio", "Pluto", "Pocahontas", "Pongo", "Pua", "Pumbaa",
    "Quasimodo", "Queen Elinor", "Queen of Hearts",
    "Rafiki", "Ralph", "Ramone", "Rapunzel", "Ray (Princess and the Frog)", "Remy", "Rex", "Rhino (Bolt)", "Riley Andersen", 
    "Robin Hood", "Roger Radcliffe", "Rolly", "Roz", "Russell",
    "Sadness", "Sarabi", "Sarafina", "Scar", "Scrooge McDuck", "Sebastian", "Shang", "Shenzi", "Shere Khan", "Simba", "Slinky Dog", 
    "Smee", "Snow White", "Sofia the First", "Sour Bill", "Stitch", "Sully", "Sven",
    "Tamatoa", "Tantor", "Tarzan", "Terk", "Tiana", "Tigger", "Timon", "Tinker Bell", "Tito", "Tod", "Tramp", "Trigger (Robin Hood)", "Trusty",
    "Ursula",
    "Vanellope", "Violet Parr", "Vitani",
    "WALL‑E", "Wendy Darling", "Wheezy", "White Rabbit", "Wilbur Robinson", "Will Turner (Pirates)", "Winnie the Pooh", "Woody",
    "Yao", "Yax", "Yen Sid", "Yzma",
    "Zazu", "Zed (Zombies)", "Zephyr", "Ziggy (Coco)", "Zurg"
  ],
  myth: [
    "Achilles", "Aeneas", "Aether", "Aphrodite", "Apollo", "Apsu", "Arachne", "Ares", "Artemis", "Asclepius", 
    "Ashura", "Athena", "Atlas", "Amaterasu", "Anubis", "Atum",
    "Baldur", "Bastet", "Beowulf", "Brahma", "Brigid",
    "Calypso", "Cernunnos", "Cerberus", "Chaos", "Charon", "Charybdis", "Circe", "Cronus",
    "Daedalus", "Dagon", "Demeter", "Dionysus", "Durga",
    "Echidna", "Eir", "Eos", "Epona", "Erebus", "Eros", "Eurydice", "Echidna",
    "Fenrir", "Freya", "Freyr", "Fujin",
    "Ganesha", "Gaia", "Gilgamesh", "Griffin", "Guanyin",
    "Hades", "Hathor", "Hecate", "Heimdall", "Hel", "Hephaestus", "Hera", "Hermes", "Hestia", "Horus", "Hunab Ku", "Hercules",
    "Icarus", "Indra", "Inanna", "Ishtar", "Isis", "Inari", "Imhotep",
    "Janus", "Jinn", "Jormungandr", "Jupiter", "Jason",
    "Kali", "Kamaitachi", "Kappa", "Kitsune", "Kraken", "Ku", "King Arthur", 
    "Loki", "Lugh", "Luna", "Lady of the Lake",
    "Marduk", "Maui", "Medusa", "Minerva", "Minotaur", "Mithras", "Morrigan", "Morgana", "Merlin", "Mordred",
    "Naga", "Nammu", "Nemesis", "Nephthys", "Neptune", "Nergal", "Njord", "Nyx", "Nurarihyon",
    "Odin", "Oni", "Osiris",
    "Pan", "Pele", "Pegasus", "Persephone", "Perseus", "Poseidon", "Prometheus",
    "Quetzalcoatl",
    "Ra", "Rama", "Ravana", "Rhea", "Ryujin",
    "Set", "Shiva", "Sigurd", "Sif", "Sirens", "Sisyphus", "Sobek", "Sun Wukong", "Susanoo", "Scylla", 
    "Tanuki", "Taweret", "Theseus", "Thor", "Tiamat", "Tlaloc", "Tyr",
    "Ullr", "Uranus",
    "Valkyrie", "Vishnu", "Vulcan",
    "Wendigo",
    "Xolotl",
    "Yama", "Ymir", "Yokai", "Yuki‑Onna",
    "Zeus", "Zhong Kui"
  ],
  borrowed: [
    "abacus", "adios", "aficionado", "al dente", "al fresco", "algebra", "alibi", "almanac", "almond", "aloha", "amigo", 
    "anime", "antipasto", "aperitif", "apricot",
    "babushka", "bagel", "baklava", "ballet", "banjo", "bazaar", "beignet", "bikini", "blitz", "blizzard", "bon appétit", 
    "bon voyage", "bonsai", "bossa nova", "bouquet", "bravo", "brioche", "bruschetta", "burrito",
    "café", "calamari", "camaraderie", "cannoli", "caramel", "carte blanche", "caviar", "chaos", "charisma", "chef", 
    "chic", "chihuahua", "chimichanga", "chow mein", "cigar", "cognac", "croissant", "cuisine", "curry",
    "déjà vu", "doppelgänger", "dormant", "dynamo",
    "eclair", "emoji", "ensemble", "entrepreneur", "espresso", "etiquette",
    "fajita", "falafel", "faux pas", "fiancé", "fiesta", "flamenco", "fondue", "fresco", "frittata",
    "gelato", "ginkgo", "gnocchi", "gourmet", "guacamole", "guerilla", "guitar",
    "haiku", "hammock", "hibachi", "hummus", "hurricane",
    "jalapeño", "judo", "juggernaut",
    "kaleidoscope", "karaoke", "ketchup", "kimono", "kindergarten", "klutz", "koala", "koi", "kosher", "kung fu",
    "latte", "linguine", "lo mein", "macaron", "macaroni", "macho", "magma", "manga", "mantra", "maracas", "masala", 
    "matador", "mattress", "memento", "miso", "mocha", "mochi", "mosquito", "mousse", "muesli", "mulatto",
    "nacho", "naive", "ninja", "noodle", "nouveau", "nugget",
    "omelette", "opera", "origami", "ottoman",
    "paparazzi", "pasta", "patio", "peacoat", "piñata", "piranha", "pizza", "plaza", "polka", "poncho", "pretzel", 
    "prima donna", "pro bono", "pueblo",
    "quesadilla", "quiche", "quinoa",
    "ramen", "ravioli", "ricotta", "risotto", "robot", "rouge", "ruckus",
    "safari", "salsa", "samosa", "sauna", "schnitzel", "schmooze", "schmutz", "schnoz", "siesta", "soprano", "soufflé", 
    "spaghetti", "sriracha", "sushi",
    "taco", "tamale", "tandoori", "tapas", "tattoo", "tempura", "teriyaki", "tofu", "tsunami", "typhoon",
    "umbrella", "umami", "utopia",
    "vaccine", "veto", "vinaigrette", "vodka", "volcano", "voyage",
    "wasabi", "wok", "won ton",
    "yoga", "yogurt", "yurt",
    "zebra", "zeitgeist", "zen", "zucchini"
  ],
  food: [
    "acai", "almond", "apple", "applesauce", "apricot", "artichoke", "arugula", "asparagus", "avocado",
    "bacon", "bagel", "baked beans", "baked potato", "banana", "barbecue rib", "barley soup", "beef", "beet", "bell pepper", 
    "biscuit", "blackberry", "blueberry", "bologna", "bread", "broccoli", "brownie", "brussels sprouts", "burger", "burrito",
    "cabbage", "cake", "calamari", "cantaloupe", "carrot", "cashew", "cauliflower", "celery", "cheese", "cheeseburger", "cheesecake", 
    "cherry", "chicken", "chicken soup", "chickpea", "chili", "chocolate", "chocolate chip cookie", "clam chowder", "coconut", 
    "coleslaw", "cookie", "corn", "cornbread", "corndog", "cranberry", "croissant", "cucumber", "cupcake",
    "date", "deviled egg", "donut", "dumplings",
    "edamame", "egg", "eggplant", "enchilada",
    "falafel", "fish", "flatbread", "flan", "focaccia", "french fries",
    "garlic bread", "gelato", "gnocchi", "goat cheese", "grape", "grapefruit", "green bean", "guacamole",
    "ham", "hamburger", "hash browns", "hazelnut", "hot dog", "hummus",
    "ice cream",
    "jerky",
    "kebab", "kiwi",
    "lasagna", "lemon", "lettuce", "lime", "lobster", "lo mein",
    "mac and cheese", "macaroni", "macarons", "mango", "marshmallow", "meatballs", "meatloaf", "melon", "mochi", "muffin", "mushroom",
    "nachos", 
    "oatmeal", "octopus", "olive", "omelette", "onion", "orange", "oyster",
    "pancake", "papaya", "pasta", "peach", "peanut", "pear", "pea", "pie", "pineapple", "pistachio", "pizza", "plum", 
    "pomegranate", "popcorn", "popsicle", "pork", "potato", "pretzel", "prosciutto", "pudding",
    "quiche", 
    "radish", "raisin", "ramen", "raspberries", "ravioli",  "ricotta",
    "sandwich", "salad", "salami", "salmon", "sausage", "scallops", "shrimp", "soba", "sorbet", "soup", "spaghetti", 
    "spinach", "squash", "steak", "stew", "strawberry", "sushi",
    "taco", "tamale", "tangerine", "tempura", "tilapia", "toast", "tofu", "tomato", "tortilla", "trout", "tuna", "turkey", "turnip",
    "udon",
    "vanilla ice cream", "veal", "venison",
    "waffle", "walnut", "watermelon", "wonton",
    "yam", "yogurt",
    "ziti", "zucchini"
  ],
  household: [
    "alarm clock", "apron",
    "backpack", "baking sheet", "bandage", "basket", "bathrobe", "bathtub", "bedframe", "bedspread", 
    "blanket", "blender", "bookcase", "bookshelf", "bottle opener", "bowl", "box cutter", "broom", "bucket", "butter knife",
    "cabinet", "calculator", "calendar", "candle", "candleholder", "can opener", "carpet", "ceiling fan", "chair", "chalk", 
    "charger", "cleaning cloth", "clock", "clothes hanger", "clothesline", "coffee maker", "coffee mug", 
    "comforter", "computer", "couch", "countertop", "crockpot", "curtains", "cutting board",
    "desk", "detergent", "dish rack", "dish towel", "dishwasher", "doormat", "doorstop", "dresser", "drying rack",
    "extension cord",
    "fabric softener", "fan", "faucet", "feather duster", "file cabinet", "fire extinguisher", "flashlight", 
    "flower vase", "folding chair", "fork", "freezer", "fridge", "frying pan",
    "garbage bag", "garbage can", "garden hose", "glasses", "glue", "grater",
    "hairbrush", "hairdryer", "hamper", "hand towel", "hanger", "heater", "highlighter",
    "ice tray", "iron", "ironing board",
    "jar", "jug",
    "kettle", "keychain", "knife",
    "ladle", "lamp", "laundry basket", "laundry detergent", "light switch", "lint roller", "lotion",
    "magnet", "measuring cup", "microwave", "mirror", "mixing bowl", "mop", "mousepad", "mug",
    "napkin", "nightstand", "notebook",
    "oven", "oven mitt",
    "pan", "paper towel", "paperclip", "pepper shaker", "pillow", "pillowcase", "pitcher", "plate", "plunger", "pot", "printer",
    "radiator", "refrigerator", "remote control", "rolling pin", "rug",
    "safety pin", "salt shaker", "scissors", "scrub", "shampoo", "sheet", "shelf", "shoe rack", "shower curtain", 
    "shower head", "sink", "skillet", "soap dispenser", "sofa", "spatula", "spice rack", "sponge", "spoon", "spray bottle", 
    "stool", "stove", "strainer", "suitcase",
    "table", "table lamp", "tablecloth", "teapot", "thermometer", "thermos", "tissue box", "toaster", "toilet paper", 
    "toilet plunger", "tongs", "toothbrush", "toothpaste", "towel", "trash can", "tray",
    "vacuum", "vase",
    "wardrobe", "washcloth", "washing machine", "water bottle", "whisk", "window", "wok", "wooden spoon",
    "yoga mat",
    "zipper bag"
  ],
};

export const DIFFICULTIES: { value: Difficulty; label: string }[] = [
  { value: "easy", label: "Easy" },
  { value: "medium", label: "Medium" },
  { value: "hard", label: "Hard" },
  { value: "impossible", label: "Impossible" },
  { value: "pokemonGen1", label: "Pokemon Gen 1"},
  { value: "slayTheSpire1", label: "Slay the Spire 1"},
  { value: "smash", label: "Smash Characters"},
  { value: "disney", label: "Disney+Pixar Characters"},
  { value: "myth", label: "Mythological Characters"},
  { value: "borrowed", label: "Borrowed Words Into English"},
  { value: "food", label: "Food"},
  { value: "household", label: "Around the House"},
];
