export type Difficulty = "easy" | "medium" | "hard" | "impossible";

export const WORD_LISTS: Record<Difficulty, string[]> = {
  easy: [
    "airport", "apple", 
    "backpack", "backyard", "ball", "banana", "bank", "basement", 
    "bathroom", "beach", "bed", "bedroom", "blanket", "boat", "book", "bottle", "broom", "bucket", "burger", 
    "cake", "candle", "candy", "car", "card", "chair", "classroom", "cat", "chocolate",
    "clock", "cloud", "comb", "cookie", "crayon", "cup", "cherry",
    "dog", "door", "drum", 
    "egg", 
    "farm", "fence", "fire", "flower", "fork", "forest", 
    "garage", "garden", "glue", "grass", 
    "hammer", "hat", "heart", "hospital", "hotel", "house", 
    "ice cream", "island", 
    "juice", "jacket",
    "key", "kitchen", "kite", "knife", 
    "ladder", "lake", "lamp", "library", "living room", 
    "mall", "marker", "milk", "mirror", "moon", "mountain", 
    "movie theater", "museum", 
    "notebook", 
    "ocean",  
    "pancake", "paper", "park", "pencil", "penny", "phone", "piano", 
    "pillow", "pizza", "plant", "plate", "playground", "pool", "pen",
    "restaurant", 
    "sandwich", "school", "scissors", "shoe", "soap", 
    "socks", "spoon", "stove", "sun", 
    "table", "toothbrush", "toothpaste", "toy", "train", "tree", "truck", "towel", 
    "wallet", "water", 
  ],
  medium: [
    "accordion", "airplane", "alligator", "almond", "Amazon", "anchor", "Albert Einstein", "apron", "aquarium", "arrow", "Avengers", "avocado", 
    "badge", "bakery", "balloon", "barbecue", "barn", "baseball", "basket", "Batman", "beaver", "beehive", "bench", "Barbie",
    "binoculars", "blender", "blueberry", "boathouse", "bookstore", "bowling alley", "bracelet", "bridge", "broccoli", "bubblegum", 
    "cabin", "cactus", "calendar", "camera", "canoe", "caramel", "carrot", "cartoon", "castle",
    "catfish", "ceiling fan", "chimney", "cinnamon", "circus", "cliff", "Coca-Cola", "compass",
    "cookie dough", "coral reef", "cottage", "crayon box", "crow", "cupcake", 
    "daffodil", "dandelion", "dartboard", "desert", "diner", "dolphin", "dragonfly", "drumstick", "Disneyland",
    "eagle", "earmuffs", "eggplant", "escalator", "Eiffel Tower",
    "Facebook", "ferry", "fireplace", "fishing pier", "flamingo", "floodlight", "flower shop", "fountain", "fox", 
    "globe", "goose", "grapefruit", "greenhouse", "guitar", "Grand Canyon", "Great Wall of China", "George Washington", "Google",
    "hamster", "hedgehog", "helmet", "honeycomb", "hot air balloon", "Hulk", "Hollywood",
    "ice rink", "igloo", "Instagram", 
    "jellybean", "jungle", 
    "kayak", "kettle", "kiwi", 
    "ladder", "lake", "lantern", "laundromat", "lemonade", "library", "Lego", "lighthouse", "lobster", 
    "magnet", "Mario", "meadow", "mermaid", "milkshake", "minivan", "monkey", "museum", "Mona Lisa", "Mount Everest", "Microsoft", "Mickey Mouse", 
    "nachos", "Netflix", "New York City", "noodle bowl", 
    "observatory", "octopus", "orchard", "otter", 
    "pancake", "parrot", "peacock", "peppermint", "pier", "pineapple", "plaza", "popcorn", "pretzel", "Pacific Ocean", "Pablo Picasso",
    "quilt", 
    "rainforest", "recycling bin", "resort", "robot", "roller coaster", 
    "sailboat", "sandcastle", "scarecrow", "school bus", "seashell", "Sesame Street", "shampoo",
    "skate park", "Snoopy", "snowman", "soccer field", "sparrow", "spatula", "Spider-Man", "squirrel", "stadium", "Statue of Liberty",
    "Starbucks", "subway", "sunflower", "surfboard", "sushi", "swamp", 
    "telescope", "tent", "tiger", "tornado", "tower", "tractor", "train station", "trombone", "tunnel", "turtle", 
    "Taylor Swift", "Times Square",
    "unicorn", 
    "valley", "volcano",
    "waffle", "waterfall", "whale", "Walmart", "windmill", "Winnie the Pooh", "woodpecker", "William Shakespeare", 
    "yogurt", "YouTube",
    "zebra", "zipper"
  ],
  hard: [
    "abyss", "Achilles", "Aesop", "Aphrodite", "alchemy", "allegiance", "Alcatraz", "amphibian", "amphitheater",
    "anatomy", "anomaly", "archipelago", "artichoke", "artifact", "astronaut", "astronomy", "avalanche",
    "bagpipes", "baguette", "barricade", "basilisk", "battalion", "beacon", "Beethoven", "bestiary", "blizzard",
    "boomerang", "brimstone", "burrow", 
    "cadence", "calamity", "carnivore", "catacomb", "chandelier", "chasm", "chisel", "chronicle", "cipher", "citadel", 
    "Cleopatra", "Colosseum", "conundrum", "corkscrew", "cosmos", "crescendo", "crimson", "crypt", "cyclone", 
    "Da Vinci", "decibel", "Dead Sea", "doppelganger", "dormant", "Dumbledore", "Darth Vader", "Dracula", 
    "eclipse",  "element", "emblem", "enigma", "epiphany", "epoch", "equator", "erosion", "escalator",  "espresso", "ethereal", 
    "faction", "fissure", "fondue", "fortitude", "Frida Kahlo", "frenzy", "frostbite", "fugitive", "furnace", 
    "Galileo", "garrison", "gauntlet", "gazebo", "Genghis Khan", "glacier", "gluttony", "golem", "gondola", "gravity", "Grand Canyon", 
    "harbinger", "havoc", "helix", "Hercules", "Houdini", "hurricane", 
    "illusion", "immortal", "impulse", "inertia", "infinity", "insignia", "instinct", "intrigue", "ironclad", 
    "javelin", 
    "kayak", "keystone", "kimono", "kombucha", 
    "labyrinth", "leviathan", "lore", 
    "macaron", "maelstrom", "Machu Picchu", "mandolin", "manifesto", "maracas", "Marie Curie", "mariner", "metamorphosis", 
    "metronome", "Machu Picchu", "mirage", "monolith", "Mount Rushmore",
    "nebula", "nemesis", "Nikola Tesla", "nocturnal", "nomad", 
    "obsidian", "octopus", "Odysseus", "omen", "oracle", "origami", "outpost", 
    "Panama Canal", "Pandora", "paradox", "paragon", "Parthenon", "pendulum", "Perseus", "phantom", "pilgrimage", 
    "pistachio", "plague", "pomegranate", "precipice", "prophecy",
    "quarry", "quiver", 
    "radiance", "rampart", "raptor", "relic", "reverie", "rift", "ritual", "Robin Hood", "runestone", 
    "saga", "sanctum", "sauerkraut", "sentinel", "serpent", "shard", "siege", "silhouette", "solstice", "souvenir", "sovereign", 
    "spatula", "specter", "sphinx", "spire", "stethoscope", "Stonehenge", "stratosphere", "summit", "sundial", "syndrome", 
    "tambourine", "telescope", "tempest", "terrarium", "tetanus", "tether", "threshold", "tiger shark", "tiramisu", "titan", 
    "torment", "traverse", "treadmill", "tundra", "tyrant", 
    "umbra", "undertow", "vanguard", "Vatican City", "venom", "verdict", "Voldemort", "vortex", 
    "warlord", "wasteland", "whirlpool", "Willy Wonka", "wraith", 
    "zephyr", "zenith", "zinc", "zircon", "zucchini", "Zorro"
  ],
  impossible: [
    "abacus", "abstraction", "access", "adaptation", "adjacency", "aftereffect", "algorithm",
    "ambiguity", "analysis", "anecdote", "anomaly", "anthology", "apathy",
    "apex", "archetype", "Area 51", "artifact", "ascension", "ash", "aspect", "atmosphere", "Atlantis", "aura",
    "Ada Lovelace", "Alan Turing", "Amelia Earhart", "atmosphere",
    "balance", "belief", "Bermuda Triangle", "bias", "Blackbeard", "boundary", "budget", "bureaucracy", 
    "cadence", "cause", "center", "charisma", "charge", "choice", "chronology", "cipher", "climate", "community", "complexity", 
    "concept", "conscience", "consensus", "context", "contrast", "control", "culture", "cycle", 
    "dark horse", "data", "decay", "definition", "demand", "desire", "destiny", "detail", "determinism", "dimension", "discourse", 
    "disparity", "distance", "draft", "drift", "dust", 
    "echo", "effect", "emotion", "empathy", "entropy", "equilibrium", "essence", "ethics", "evidence", 
    "evolution", "exception", "experience", "factor", "fear", "feedback", "field", "fine print", "Fibonacci", "flame", "focus", 
    "foam", "force", "form", "frame", "frequency", "function", 
    "galaxy", "gateway", "genre", "government", "grain", "growth", 
    "habit", "Harriet Tubman", "harmony", "heuristic", "history", "horizon", "hypothesis", 
    "idea", "identity", "impact", "impulse", "incentive", "inference", "infinity", "inkwell", "instinct",
    "intention", "interaction", "interpretation", "irony", 
    "Jane Austen", 
    "karma", "knowledge", "Kyoto", "layer",
    "limit", "limbo", "loophole", "Luxembourg", 
    "market", "Mary Shelley", "matter", "meaning", "mechanism", "memory", "metaphor", "method", "Mongolia", 
    "momentum", "Monet", "moss", "motion", "Murphy's law", "mystique",
    "nature", "necessity", "nostalgia", "notion", 
    "observation", "Occam's razor", "ocean", "offset", "origin", "Ssaka", "Oscar Wilde", "outcome", 
    "parallel", "pattern", "perception", "perspective", "phenomenon", "philosophy", "plot twist", "Pythagoras", 
    "quality", "Quebec", "quill", "range", "Rasputin", "reaction", "reason", "red herring", "reflection", "reputation", "resolution", 
    "resource", "risk", "Rosetta Stone", "root", 
    "Sahara Desert", "Scherodinger's cat", "season", "Sicily", "Signal", "Sisyphus", "society", "space", "stereoscope", "steam", 
    "structure", "substance", "supply", "surface", "symbol", "system", 
    "tension", "technology", "tendency", "theory", "thread", "thought", "trade", "tradition", "Trojan Horse", "truth", "turbulence", 
    "union", "Uluru", 
    "value", "Vancouver", "variable", "version", "vibration", "volume", 
    "wave", "wealth", "weather", "will", "wisdom", "wonder", "world", 
    "z-axis", "zen", "zero", "zone",
  ],
};

export const DIFFICULTIES: { value: Difficulty; label: string }[] = [
  { value: "easy", label: "Easy" },
  { value: "medium", label: "Medium" },
  { value: "hard", label: "Hard" },
  { value: "impossible", label: "Impossible" },
];
