/** Order decks for Order Overload. Common items have multiple copies. */

const cafeEntries: [string, number][] = [
  // Coffee drinks — common
  ["Hot Coffee", 5],
  ["Iced Coffee", 5],
  ["Hot Latte", 5],
  ["Iced Latte", 5],
  ["Cappuccino", 3],
  ["Espresso", 2],
  ["Double Espresso", 2],
  ["Cold Brew Coffee", 2],

  // Tea drinks — common
  ["Iced Lemon Tea", 3],
  ["Iced Milk Tea", 3],
  ["Hot Tea", 3],
  ["Bubble Milk Tea", 2],
  ["Matcha Latte", 2],

  // Specialty coffee
  ["Caramel Macchiato", 2],
  ["Cafe Mocha", 2],
  ["Soy Latte", 2],
  ["Almond Caramel Latte", 1],
  ["Extra Hot Cafe Latte", 1],
  ["Room Temperature Coffee", 1],
  ["Iced Coffee Without Ice", 1],

  // Non-coffee/tea drinks
  ["Orange Juice", 2],
  ["Apple Juice", 2],
  ["Chocolate Shake", 1],
  ["Vanilla Shake", 1],
  ["Banana Shake", 1],
  ["Strawberry Milk", 1],
  ["Banana Milk", 1],
  ["Milk", 1],
  ["Lemonade", 1],

  // Foods
  ["Apple Pie", 2],
  ["Ham & Cheese Sandwich", 2],
  ["Hot Ham & Cheese Sandwich", 1],
  ["Chocolate Gateau", 2],
  ["Cinnamon Roll", 1],
  ["Glazed Donut", 1],
  ["Pancake", 1],
  ["Mille Crepe", 1],
  ["Egg Sandwich", 1],
  ["French Toast", 1],
  ["Banana", 1],
  ["Chocolate Chip Cookie", 1],
  ["Tuna Sandwich", 1],
  ["Cheese Cake", 1],
  ["Lemon Cake", 1],
  ["Chiffon Cake", 1],
  ["Chocolate Croissant", 1],
  ["Banana Muffin", 1],
];

const mtgEntries: [string, number][] = [
  // Creatures — common
  ["Llanowar Elves", 4],
  ["Grizzly Bears", 3],
  ["Serra Angel", 3],
  ["Shivan Dragon", 2],
  ["Mother of Runes", 2],
  ["Prodigal Sorcerer", 2],
  ["Royal Assassin", 2],
  ["Sengir Vampire", 2],
  ["Air Elemental", 2],
  ["Tarmogoyf", 1],
  ["Snapcaster Mage", 1],
  ["Dark Confidant", 1],
  ["Goblin Guide", 1],
  ["Thalia", 1],
  ["Delver of Secrets", 1],
  ["Emrakul", 1],
  ["Nicol Bolas", 1],
  ["Craterhoof Behemoth", 1],
  ["Wurmcoil Engine", 1],
  ["Blightsteel Colossus", 1],
  ["Stoneforge Mystic", 1],
  ["Young Pyromancer", 1],

  // Instants & sorceries
  ["Lightning Bolt", 3],
  ["Counterspell", 3],
  ["Giant Growth", 2],
  ["Dark Ritual", 2],
  ["Swords to Plowshares", 1],
  ["Wrath of God", 2],
  ["Swords to Plowshares", 2],
  ["Path to Exile", 1],
  ["Brainstorm", 1],
  ["Demonic Tutor", 1],
  ["Ancestral Recall", 1],
  ["Time Walk", 1],

  // Artifacts
  ["Sol Ring", 2],
  ["Black Lotus", 1],
  ["Nevinyrral's Disk", 1],
  ["Aether Vial", 1],
  ["Chrome Mox", 1],
  ["Chalice of the Void", 1],
];

const duckduckGooseEntries: [string, number][] = [
  ["Duck", 5],
  ["Canada Goose", 5],
  ["Squirrel", 5],
  ["Birb", 5],
  ["Chipmunk", 3],
  ["Doggo", 3],
  ["Baby Duck", 3],
  ["Smol Birb", 3],
  ["Psyduck", 2],
  ["Rubber Duck", 2],
  ["Tortle", 2],
  ["Baby Goose", 2],
  ["Hummingbirb", 2],
  ["Chubby Squirrel", 2],
  ["Corgi", 2],
  ["Cucco", 2],
  ["Bunny", 2],
  ["Mama Goose", 2],
  ["Hawaiian Goose", 2],
  ["Pikmin", 2],
  ["Froggo", 2],
  ["Aflac Duck", 1],
  ["Snake", 1],
  ["Donald Duck", 1],
  ["Duck Hunt Duck", 1],
  ["Duck Hunt Doggo", 1],
  ["Doog", 1],
  ["Maya", 1],
  ["Untitled Goose with a Knife", 1],
  ["Rubber Duck w/ Sunglasses", 1],
  ["Squirtle", 1],
  ["Teenage Mutant Ninja Turtle", 1],
  ["Chubby Squirrel w/ a French Fry", 1],
  ["Chip & Dale", 1],
  ["Skunk", 1],
  ["Roast Duck", 1],
  ["Peking Duck", 1],
  ["Angry Mama Goose", 1],
  ["Ugly Baby Duck", 1],
  ["Wet Doggo", 1],
  ["Mushroom", 1],
  ["Flamingogo", 1],
  ["DuckDuckGo", 1],
  ["Bugs Bunny", 1],
  ["Salamander", 1],
  ["Barking Doggo", 1],
  ["Shuckle", 1],
];

const pokemonEntries: [string, number][] = [
  // === Original (mostly Gen 1 + Eeveelutions) ===
  ["Rattata", 5],
  ["Pidgey", 5],
  ["Zubat", 5],
  ["Paras", 5],
  ["Raticate", 3],
  ["Pidgeotto", 3],
  ["Golbat", 3],
  ["Staryu", 3],
  ["Pidgeot", 2],
  ["Parasect", 2],
  ["Growlithe", 2],
  ["Starmie", 2],
  ["Exeggcute", 2],
  ["Spearow", 2],
  ["Fearow", 2],
  ["Slowpoke", 2],
  ["Jigglypuff", 2],
  ["Sandshrew", 2],
  ["Meowth", 2],
  ["Pikachu", 2],
  ["Eevee", 2],
  ["Pichu", 1],
  ["Vaporeon", 1],
  ["Jolteon", 1],
  ["Flareon", 1],
  ["Espeon", 1],
  ["Umbreon", 1],
  ["Leafeon", 1],
  ["Glaceon", 1],
  ["Sylveon", 1],
  ["Arcanine", 1],
  ["Alolan Raichu", 1],
  ["Slowbro", 1],
  ["Raichu", 1],
  ["Mew", 1],
  ["Mewtwo", 1],
  ["Exeggutor", 1],          // fixed typo (was Exeggcutor)
  ["Sandslash", 1],
  ["Bulbasaur", 1],
  ["Charmander", 1],
  ["Squirtle", 1],
  ["Ditto", 1],
  ["Zapdos", 1],
  ["Articuno", 1],            // removed duplicate
  ["Moltres", 1],
  ["Shuckle?!", 1],

  // === Gen 4–6 ===
  ["Lucario", 2],
  ["Garchomp", 2],
  ["Togekiss", 1],
  ["Rotom", 2],
  ["Giratina", 1],
  ["Darkrai", 1],
  ["Gallade", 1],
  ["Weavile", 1],
  ["Roserade", 1],
  ["Toxicroak", 1],
  ["Froslass", 1],
  ["Dusknoir", 1],
  ["Magnezone", 1],
  ["Electivire", 1],
  ["Magmortar", 1],
  ["Togetic", 1],
  ["Riolu", 2],
  ["Gible", 2],
  ["Gabite", 1],

  // === Gen 7 ===
  ["Rowlet", 3],
  ["Litten", 3],
  ["Popplio", 3],
  ["Decidueye", 1],
  ["Incineroar", 1],
  ["Primarina", 1],
  ["Lycanroc", 2],
  ["Mimikyu", 2],
  ["Toxapex", 1],
  ["Nihilego", 1],
  ["Buzzwole", 1],
  ["Pheromosa", 1],
  ["Xurkitree", 1],
  ["Celesteela", 1],
  ["Kartana", 1],
  ["Guzzlord", 1],
  ["Necrozma", 1],
  ["Magearna", 1],
  ["Marshadow", 1],
  ["Zeraora", 1],
  ["Melmetal", 1],
  ["Alolan Ninetales", 1],
  ["Alolan Marowak", 1],
  ["Alolan Muk", 1],
  ["Alolan Exeggutor", 1],
  ["Wishiwashi", 1],
  ["Araquanid", 1],
  ["Salazzle", 1],
  ["Tsareena", 1],
  ["Comfey", 1],
  ["Oranguru", 1],
  ["Passimian", 1],
  ["Palossand", 1],
  ["Minior", 1],
  ["Kommo-o", 1],

  // === Gen 8 ===
  ["Grookey", 3],
  ["Scorbunny", 3],
  ["Sobble", 3],
  ["Rillaboom", 1],
  ["Cinderace", 1],
  ["Inteleon", 1],
  ["Corviknight", 2],
  ["Dragapult", 1],
  ["Toxtricity", 1],
  ["Zacian", 1],
  ["Zamazenta", 1],
  ["Eternatus", 1],
  ["Urshifu", 1],
  ["Zarude", 1],
  ["Calyrex", 1],
  ["Regieleki", 1],
  ["Regidrago", 1],
  ["Glastrier", 1],
  ["Spectrier", 1],
  ["Cramorant", 1],
  ["Sirfetch'd", 1],
  ["Mr. Rime", 1],
  ["Runerigus", 1],
  ["Alcremie", 1],
  ["Falinks", 1],
  ["Pincurchin", 1],
  ["Frosmoth", 1],
  ["Stonjourner", 1],
  ["Eiscue", 1],
  ["Indeedee", 1],
  ["Morpeko", 1],
  ["Copperajah", 1],
  ["Duraludon", 1],
  ["Dreepy", 2],
  ["Drakloak", 1],
  ["Impidimp", 2],
  ["Morgrem", 1],
  ["Grimmsnarl", 1],
  ["Hatenna", 2],
  ["Hattrem", 1],
  ["Hatterene", 1],

  // === Gen 9 ===
  ["Sprigatito", 3],
  ["Fuecoco", 3],
  ["Quaxly", 3],
  ["Meowscarada", 1],
  ["Skeledirge", 1],
  ["Quaquaval", 1],
  ["Annihilape", 1],
  ["Baxcalibur", 1],
  ["Gholdengo", 1],
  ["Miraidon", 1],
  ["Koraidon", 1],
  ["Ogerpon", 1],
  ["Terapagos", 1],
  ["Okidogi", 1],
  ["Munkidori", 1],
  ["Fezandipiti", 1],
  ["Pecharunt", 1],
  ["Walking Wake", 1],
  ["Iron Leaves", 1],
  ["Gouging Fire", 1],
  ["Raging Bolt", 1],
  ["Iron Boulder", 1],
  ["Iron Crown", 1],
  ["Ting-Lu", 1],
  ["Chien-Pao", 1],
  ["Wo-Chien", 1],
  ["Chi-Yu", 1],
  ["Roaring Moon", 1],
  ["Iron Valiant", 1],
  ["Great Tusk", 1],
  ["Scream Tail", 1],
  ["Brute Bonnet", 1],
  ["Flutter Mane", 1],
  ["Slither Wing", 1],
  ["Sandy Shocks", 1],
  ["Iron Treads", 1],
  ["Iron Bundle", 1],
  ["Iron Hands", 1],
  ["Iron Jugulis", 1],
  ["Iron Moth", 1],
  ["Iron Thorns", 1],
  ["Gimmighoul", 2],
  ["Tinkatink", 2],
  ["Tinkatuff", 1],
  ["Tinkaton", 1],
  ["Fidough", 2],
  ["Dachsbun", 1],
  ["Maschiff", 2],
  ["Mabosstiff", 1],
  ["Shroodle", 2],
  ["Grafaiai", 1],
  ["Bramblin", 2],
  ["Brambleghast", 1],
  ["Toedscool", 2],
  ["Toedscruel", 1],
  ["Klawf", 1],
  ["Capsakid", 2],
  ["Scovillain", 1],
  ["Rellor", 2],
  ["Rabsca", 1],
  ["Flittle", 2],
  ["Espathra", 1],
  ["Tandemaus", 2],
  ["Maushold", 1],
  ["Cetoddle", 2],
  ["Cetitan", 1],
  ["Veluza", 1],
  ["Dondozo", 1],
  ["Tatsugiri", 1],
  ["Clodsire", 1],
  ["Farigiraf", 1],
  ["Dudunsparce", 1],
  ["Kingambit", 1],
  ["Frigibax", 2],
  ["Arctibax", 1],
  ["Wooper", 2],
];

const bobaCafeEntries: [string, number][] = [
  ["Jasmine Green Milk Tea", 5],
  ["Black Milk Tea", 5],
  ["Brown Sugar Milk Tea", 5],
  ["Taro Milk Tea", 5],
  ["Oolong Milk Tea", 3],
  ["Classic Pearl Milk Tea", 3],
  ["Hokkaido Milk Tea", 3],
  ["Okinawa Milk Tea", 3],
  ["Matcha Red Bean Milk Tea", 2],
  ["Peach Tea", 2],
  ["Coconut Milk Tea", 2],
  ["Thai Milk Tea", 2],
  ["Chocolate Milk Tea", 2],
  ["Honeydew Milk Tea", 2],
  ["Lavender Milk Tea", 2],
  ["Earl Grey Milk Tea", 2],
  ["Almond Milk Tea", 2],
  ["Wintermelon Milk Tea", 2],
  ["Coffee Milk Tea", 2],
  ["Roasted Oolong Milk Tea", 1],
  ["Passion Fruit Tea", 1],
  ["Lychee Tea", 1],
  ["Mango Tea", 1],
  ["Strawberry Tea", 1],
  ["Dragon Fruit Tea", 1],
  ["Lemon Tea", 1],
  ["Watermelon Tea", 1],
  ["Brown Sugar Milk Tea with 50% Sugar", 1],
  ["Brown Sugar Milk", 1],
  ["Classic Pearl Milk Tea without Boba", 1],
  ["Classic Pearl Milk Tea without Ice", 1],
  ["Jasmine Green Milk Tea without Ice", 1],
  ["Oolong Milk Tea with 30% Sugar, No Ice", 1],
  ["Mango Pomelo Tea", 1],
  ["Brown Sugar Milk Tea with 30% Sugar", 1],
  ["Taro Milk Tea with Fresh Taro", 1],
  ["Mango Tea with Lychee jelly", 1],
  ["Mango Tea with Herbal Jelly", 1],
  ["Brown Sugar Milk Tea without Boba", 1],
  ["Oolong Milk Tea with 30% sugar", 1],
  ["Taro Milk Tea without Boba", 1],
  ["Peach Tea with no Sugar", 1],
  ["Original Yakult Green Tea", 1],
  ["Passion Fruit Yakult", 1],
  ["Mango Yakult", 1],
  ["Tieguanyin Boba Tea", 1],
  ["Brown Sugar Milk Tea with Ube Cream Cheese and Mochi", 1],
];

const stsEntries: [string, number][] = [
  ["Strike", 5],
  ["Defend", 5],
  ["Pommel Strike", 5],
  ["Perfected Strike", 5],
  ["Poisoned Stab", 3],
  ["Deadly Poison", 3],
  ["Twin Strike", 3],
  ["Dagger Spray", 3],
  ["Dagger Throw", 2],
  ["Ball Lightning", 2],
  ["Leg Sweep", 2],
  ["Backstab", 2],
  ["Hemokinesis", 2],
  ["Zap", 2],
  ["Bouncing Flask", 2],
  ["Glacier", 2],
  ["Flame Barrier", 2],
  ["Sweeping Beam", 2],
  ["Double Energy", 2],
  ["Shockwave", 1],
  ["Tactician", 1],
  ["Cold Snap", 1],
  ["Jack of All Trades", 1],
  ["Feed", 1],
  ["Finesse", 1],
  ["Overclock", 1],
  ["Neutralize", 1],
  ["Shrug It Off", 1],
  ["True Grit", 1],
  ["Turbo", 1],
  ["Slice", 1],
  ["Skim", 1],
  ["Skewer", 1],
  ["All For One", 1],
  ["Chill", 1],
  ["Buffer", 1],
  ["Bludgeon", 1],
  ["Blur", 1],
  ["Body Slam", 1],
  ["Dark Embrace", 1],
  ["Flame Barrier", 1],
  ["Claw", 1],
  ["Flash of Steel", 1],
  ["Hand of Greed", 1],
  ["Feel No Pain", 1],
  ["Dramatic Entrance", 1],
  ["Go for the Eyes", 1],
  ["Echo Form", 1],
  ["Demon Form", 1],
  ["Wraith Form", 1],
];

const cheeseEntries: [string, number][] = [
  ["Cheese", 5],
  ["Goat Cheese", 5],
  ["Blue Cheese", 5],
  ["Swiss Cheese", 5],
  ["American Cheese", 5],
  ["String Cheese", 3],
  ["Cream Cheese", 3],
  ["Cottage Cheese", 3],
  ["Cheddar", 2],
  ["Smoked Cheddar", 2],
  ["Monterey Jack", 2],
  ["Colby Jack", 2],
  ["Pepper Jack", 2],
  ["Mozzarella", 2],
  ["Provolone", 2],
  ["Gouda", 1],
  ["Parmesan", 1],
  ["Feta", 1],
  ["Brie", 1],
  ["Gruyère", 1],
  ["Ricotta", 1],
  ["Mascarpone", 1],
  ["Burrata", 1],
  ["Halloumi", 1],
  ["Manchego", 1],
  ["Camembert", 1],
  ["Cheetos", 1],
  ["Mac and Cheese", 1],
  ["Cheese Quesadilla", 1],
  ["Cheese Soufflé", 1],
  ["Fondue", 1],
  ["Cheese Platter", 1],
  ["Cheese Omelette", 1],
  ["Cheese Spread", 1],
];

const steakhouseEntries: [string, number][] = [
  ["Steak", 5],
  ["Ribeye Steak", 5],
  ["New York Strip Steak", 5],
  ["T‑Bone Steak", 5],
  ["Sirloin Steak", 3],
  ["Porterhouse Steak", 3],
  ["Prime Rib", 3],
  ["Tomahawk Steak", 3],
  ["Flat Iron Steak", 2],
  ["Flank Steak", 2],
  ["Skirt Steak", 2],
  ["Filet Mignon", 2],
  ["Rare Steak", 2],
  ["Medium‑Rare Steak", 2],
  ["Medium Steak", 2],
  ["Medium‑Well Steak", 2],
  ["Well‑Done Steak", 2],
  ["French Fries", 2],
  ["Sweet Potato Fries", 2],
  ["Steak Fries", 2],
  ["Baked Potato", 2],
  ["Loaded Baked Potato", 2],
  ["Mashed Potatoes", 2],
  ["Mac and Cheese", 2],
  ["Corn on the Cob", 2],
  ["Garlic Bread", 2],
  ["Grilled Asparagus", 1],
  ["Green Beans", 1],
  ["Sautéed Mushrooms", 1],
  ["Onion Rings", 1],
  ["Blooming Onion", 1],
  ["House Salad", 1],
  ["Caesar Salad", 1],
  ["Dinner Rolls", 1],
  ["Cheese Bread", 1],
  ["Calamari", 1],
  ["Cheesecake", 1],
  ["Chocolate Cake", 1],
  ["Apple Pie", 1],
  ["Beer", 2],
  ["Draft Beer", 1],
  ["Red Wine", 2],
  ["White Wine", 2],
  ["Whiskey", 1],
  ["Iced Tea", 1],
  ["Lemonade", 1],
  ["Medium‑Rare Steak With No Sauce", 1],
  ["Medium‑Rare Steak With Sauce on the Side", 1],
  ["Medium‑Well Steak With No Sauce", 1],
  ["Medium‑Well Steak With Sauce on the Side", 1],
  ["Extra Rare Steak", 1],
  ["Extra Well‑Done Steak", 1],
  ["T‑Bone Steak with no T-bone", 1],
];

const sushiEntries: [string, number][] = [
  ["California Roll", 5],
  ["Spicy Tuna Roll", 5],
  ["Tuna Roll", 5],
  ["Tuna Nigiri", 5],
  ["Tuna Sashimi", 5],
  ["Salmon Nigiri", 5],
  ["Salmon Sashimi", 5],
  ["Unagi Sashimi", 5],
  ["Unagi Nigiri", 5],
  ["Tamago Nigiri", 3],
  ["Salmon Skin Roll", 3],
  ["Rainbow Roll", 3],
  ["Dragon Roll", 3],
  ["Chirashi Bowl", 3],
  ["Avocado Roll", 3],
  ["Maguro Nigiri", 1],
  ["Ebi Nigiri", 1],
  ["Philadelphia Roll", 2],
  ["Hamachi Nigiri", 1],
  ["Unagi Roll", 2],
  ["Unagi Temaki", 2],
  ["Shrimp Tempura Roll", 2],
  ["Salmon Maki", 2],
  ["Salmon Roll", 2],
  ["Spicy Salmon Roll", 2],
  ["Tuna Maki", 2],
  ["Yellowtail Nigiri", 2],
  ["Yellowtail Sashimi", 2],
  ["Yellowtail Maki", 2],
  ["Spicy Shrimp Roll", 1],
  ["Sake Nigiri", 1],
  ["Toro Nigiri", 2],
  ["Caterpillar Roll", 1],
  ["Spider Roll", 1],
  ["Alaska Roll", 1],
  ["Inari Sushi", 1],
  ["Boston Roll", 1],
  ["Uni Nigiri", 1],
  ["Uni Sashimi", 1],
  ["Edamame", 2],
  ["Gyoza", 2],
  ["Miso Soup", 2],
  ["Beer", 1],
  ["Matcha Tea", 1],
  ["Extra Wasabi", 1],
  ["Extra Ginger", 1],
  ["California Roll with Extra Wasabi", 1],
  ["California Roll with Extra Ginger", 1],
  ["Tuna Nigiri with half rice", 1],
  ["Salmon Nigiri with half rice", 1],
  ["Unagi Nigiri with half rice", 1],
  ["Tuna Roll with Extra Wasabi", 1],
  ["Tuna Roll with Extra Ginger", 1],
  ["Chirashi Bowl with no rice", 1],
  ["Extra Fatty Toro Nigiri", 1],
];


/** Registry of available decks. */
export const DECKS: Record<string, { label: string; entries: [string, number][] }> = {
  cafe: { label: "Cafe", entries: cafeEntries },
  duckDuckGoose: { label: "Duck Duck Goose", entries: duckduckGooseEntries },
  mtg: { label: "Magic: The Gathering", entries: mtgEntries },
  pokemon: { label: "Pokémon", entries: pokemonEntries, },
  bobaCafe: { label: "Boba Cafe", entries: bobaCafeEntries, },
  slayTheSpire: { label: "Slay the Spire", entries: stsEntries, },
  cheese: { label: "Cheese", entries: cheeseEntries, },
  steakhouse: { label: "Steakhouse", entries: steakhouseEntries, },
  sushi: { label: "Sushi", entries: sushiEntries, },
};

function flatten(entries: [string, number][]): string[] {
return entries.flatMap(([name, count]) =>
  Array.from({ length: count }, () => name)
);
}

/** Get the flat deck array for a given deck ID. */
export function getDeck(deckId: string): string[] {
const deck = DECKS[deckId] ?? DECKS.cafe;
return flatten(deck.entries);
}

/** Get unique order names for a given deck ID. */
export function getUniqueOrders(deckId: string): string[] {
const deck = DECKS[deckId] ?? DECKS.cafe;
return deck.entries.map(([name]) => name);
}
